
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Dec 13 09:29:39 CET 2016
//----------------------------------------------------

package ppdz;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MOREQUAL = 35;
  public static final int LBRACKET = 12;
  public static final int INCREMENT = 24;
  public static final int CHAR = 42;
  public static final int CONST = 7;
  public static final int EQUALS = 32;
  public static final int STRCONST = 44;
  public static final int LPAREN = 5;
  public static final int SEMI = 8;
  public static final int LESS = 36;
  public static final int MINUS = 29;
  public static final int DECREMENT = 25;
  public static final int RPAREN = 6;
  public static final int AND = 26;
  public static final int LESSEQUAL = 37;
  public static final int NEQUALS = 33;
  public static final int OR = 27;
  public static final int COMMA = 10;
  public static final int CLASS = 14;
  public static final int DIV = 39;
  public static final int PLUS = 31;
  public static final int ASSIGN = 9;
  public static final int IF = 22;
  public static final int DOT = 28;
  public static final int EOF = 0;
  public static final int RETURN = 19;
  public static final int RBRACKET = 13;
  public static final int NEW = 30;
  public static final int error = 1;
  public static final int PERCENT = 40;
  public static final int NUMBER = 41;
  public static final int IDENT = 45;
  public static final int BREAK = 18;
  public static final int VOID = 11;
  public static final int TIMES = 38;
  public static final int LBRACE = 3;
  public static final int ELSE = 23;
  public static final int READ = 17;
  public static final int WHILE = 16;
  public static final int RBRACE = 4;
  public static final int BOOLCONST = 43;
  public static final int EXTENDS = 15;
  public static final int PROG = 2;
  public static final int PRINT = 20;
  public static final int MORE = 34;
  public static final int DO = 21;
}

